<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Carbon;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

/**
 * Class User
 *
 * @property int $id
 * @property int|null $company_id
 * @property string|null $mobile_number
 * @property string|null $name
 * @property string|null $email
 * @property string|null $password
 * @property bool|null $is_verified
 * @property string|null $phone
 * @property string|null $avatar
 * @property bool $is_active
 * @property bool $must_change_password
 * @property Carbon|null $last_login_at
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property Carbon|null $deleted_at
 *
 * @property-read Company|null $company
 * @property-read Collection<int, Machine> $machines
 * @property-read Collection<int, Report> $reports
 * @property-read Collection<int, AuditLog> $auditLogs
 * @property-read Collection<int, Alert> $acknowledgedAlerts
 * @property-read Collection<int, Alert> $resolvedAlerts
 * @property-read Collection<int, OtpCode> $otpCodes
 * @property-read string $role
 *
 * @method static \Database\Factories\UserFactory factory($count = null, $state = [])
 */
class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasApiTokens, HasFactory, HasRoles, Notifiable, SoftDeletes;

    protected $table = 'users';

    protected $fillable = [
        'company_id',
        'mobile_number',
        'name',
        'email',
        'password',
        'is_verified',
        'phone',
        'avatar',
        'is_active',
        'must_change_password',
        'last_login_at',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'password' => 'hashed',
        'is_active' => 'boolean',
        'is_verified' => 'boolean',
        'must_change_password' => 'boolean',
        'last_login_at' => 'datetime',
    ];

    /**
     * Get the company that the user belongs to.
     *
     * @return BelongsTo<Company, $this>
     */
    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * Get the machines assigned to the user.
     *
     * @return HasMany<Machine, $this>
     */
    public function machines(): HasMany
    {
        return $this->hasMany(Machine::class, 'user_id');
    }

    /**
     * Get the reports generated by the user.
     *
     * @return HasMany<Report, $this>
     */
    public function reports(): HasMany
    {
        return $this->hasMany(Report::class, 'generated_by');
    }

    /**
     * Get the audit logs for the user.
     *
     * @return HasMany<AuditLog, $this>
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class);
    }

    /**
     * Get the alerts acknowledged by the user.
     *
     * @return HasMany<Alert, $this>
     */
    public function acknowledgedAlerts(): HasMany
    {
        return $this->hasMany(Alert::class, 'acknowledged_by');
    }

    /**
     * Get the alerts resolved by the user.
     *
     * @return HasMany<Alert, $this>
     */
    public function resolvedAlerts(): HasMany
    {
        return $this->hasMany(Alert::class, 'resolved_by');
    }

    /**
     * Get the OTP codes for the user's mobile number.
     *
     * @return HasMany<OtpCode, $this>
     */
    public function otpCodes(): HasMany
    {
        return $this->hasMany(OtpCode::class, 'mobile_number', 'mobile_number');
    }

    /**
     * Find a user by mobile number.
     *
     * @param string $mobileNumber
     * @return User|null
     */
    public static function findByMobile(string $mobileNumber): ?self
    {
        return static::where('mobile_number', $mobileNumber)->first();
    }

    /**
     * Get the user's role name.
     *
     * @return string
     */
    public function getRoleAttribute(): string
    {
        return $this->roles->first()?->name ?? '';
    }
}
