<?php

declare(strict_types=1);

namespace App\Constants;

/**
 * PermissionConstants
 *
 * Defines every permission string used by the DeskGuard authorisation
 * system. These constants pair with spatie/laravel-permission and
 * should be used in Gates, middleware, and Blade checks to avoid
 * typos and enable IDE autocompletion.
 */
class PermissionConstants
{
    /** Ability to create, edit and delete companies */
    public const string MANAGE_COMPANIES = 'manage companies';

    /** Ability to manage software licence records */
    public const string MANAGE_LICENSES = 'manage licenses';

    /** Ability to manage every user account in the system */
    public const string MANAGE_ALL_USERS = 'manage all users';

    /** Ability to view systems across all companies */
    public const string VIEW_ALL_SYSTEMS = 'view all systems';

    /** Unrestricted access to all data across the platform */
    public const string MANAGE_ALL_DATA = 'manage all data';

    /** Ability to create employee accounts within own company */
    public const string CREATE_EMPLOYEES = 'create employees';

    /** Ability to create sub-head accounts within own company */
    public const string CREATE_SUB_HEADS = 'create sub heads';

    /** Ability to remove employee accounts */
    public const string DELETE_EMPLOYEES = 'delete employees';

    /** Ability to assign or unassign machines to employees */
    public const string ASSIGN_MACHINES = 'assign machines';

    /** Ability to view systems belonging to own company */
    public const string VIEW_COMPANY_SYSTEMS = 'view company systems';

    /** Ability to access and generate reports */
    public const string VIEW_REPORTS = 'view reports';

    /** Ability to view alerts generated by monitored machines */
    public const string VIEW_ALERTS = 'view alerts';

    /** Ability to modify company-level configuration */
    public const string MANAGE_COMPANY_SETTINGS = 'manage company settings';

    /** Ability to view employees assigned to own team */
    public const string VIEW_ASSIGNED_EMPLOYEES = 'view assigned employees';

    /** Ability to view machines assigned to own team */
    public const string VIEW_ASSIGNED_MACHINES = 'view assigned machines';

    /** Ability to view only own assigned machine */
    public const string VIEW_OWN_MACHINE = 'view own machine';

    /** Ability to view alerts triggered for own machine */
    public const string VIEW_OWN_ALERTS = 'view own alerts';

    /** Ability to view reports generated for own machine */
    public const string VIEW_OWN_REPORTS = 'view own reports';
}
